### ISSUE TITLE
Take a screenshot

### ISSUE THREAD

**Issue by ilyaglow** [ilyaglow/remote-virtualbox#6]

**Comment by jacopofar** [comment]
I'm interested in adding this function and also ensure that the library works with the Virtualbox 6.*, would a PR on this be fine for you?

**Comment by ilyaglow** [comment]
It would be awesome, thanks!

**Comment by jacopofar** [comment]
I would also like to move to Python 3.6 and possibly add some integration test

**Comment by ilyaglow** [comment]
Closed in #13
